
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';

export const setupTestStudentTeacherRelationship = async (
  teacherId: string, 
  studentId: string
) => {
  try {
    // Create a test class
    const classData = await createTestClass(teacherId, 'Test Class');
    if (!classData) {
      return false;
    }
    
    // Enroll the student in the class
    const { error: enrollError } = await supabase
      .from('class_enrollments')
      .insert({
        class_id: classData.id,
        student_id: studentId
      });
    
    if (enrollError) {
      console.error('Error enrolling student:', enrollError);
      toast.error('Failed to enroll student in test class');
      return false;
    }
    
    return true;
  } catch (error) {
    console.error('Error setting up test relationship:', error);
    toast.error('Failed to set up test student-teacher relationship');
    return false;
  }
};

export const createTestClass = async (teacherId: string, className: string) => {
  try {
    const { data, error } = await supabase
      .from('classes')
      .insert({
        name: className,
        description: 'Test class created for demonstration',
        teacher_id: teacherId,
        class_code: null // Will be generated by the database trigger
      })
      .select()
      .single();
    
    if (error) {
      console.error('Error creating test class:', error);
      toast.error('Failed to create test class');
      return null;
    }
    
    return data;
  } catch (error) {
    console.error('Error in createTestClass:', error);
    toast.error('Failed to create test class');
    return null;
  }
};
