
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ogszwetzvvaqmlswrajz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9nc3p3ZXR6dnZhcW1sc3dyYWp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1OTgyMjUsImV4cCI6MjA1OTE3NDIyNX0.5LU8ETX9d8U9vAnXXtg23Mx6SxeOVJk8mngbgu8JIyE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false,
    flowType: 'implicit',
  }
});
